{
    "MODEL": "gpt-3.5-turbo-1106", #"gpt-3.5-turbo-1106","mistral-small-latest","meta.llama2-70b-chat-v1"
    "EVAL_MODEL": "gpt-4-turbo-preview", # "gpt-4-turbo-preview"
    "TEMPERATURE": 0.0, 
    "CANDIDATE_TEMPERATURE": 1.5,
    "DATASET_NAME": "freshqa", #"freshqa", "QAQA"
    "DATASET_PATH": "Data\\", # "Data\\"
    "EVIDENCE_BATCH_SAVE_PATH": "Web_Search_Response\\evidence_results_batch_serp_all_freshqa.json", 
    "QUERY_PROMPT_PATH": "Prompts\\minimal_response.txt",
    "BACKWARD_REASONING_RESP_PROMPT_PATH":"Prompts\\backward_reasoning_resp.txt",
    "BACKWARD_REASONING_QUERY_PROMPT_PATH":"Prompts\\backward_reasoning_query.txt",
    "LLAMA_QUERY_PROMPT_PATH": "Prompts\\minimal_response_meta.txt",
    "LLAMA_BACKWARD_REASONING_RESP_PROMPT_PATH":"Prompts\\backward_reasoning_resp_meta.txt",
    "LLAMA_BACKWARD_REASONING_QUERY_PROMPT_PATH":"Prompts\\backward_reasoning_query_meta.txt",
    "AUTO_EVALUATION_PROMPT_PATH": "Prompts\\eval_response_comp.txt",
    "RESULT_SAVE_PATH": "Results\\",
    "MAX_CANDIDATE_RESPONSES": 3 #default - 3
}