{
    "MODEL": "meta.llama2-70b-chat-v1",
    "EVAL_MODEL": "gpt-4-turbo-preview",
    "TEMPERATURE": 0.0,
    "CANDIDATE_TEMPERATURE": 1.0,
    "DATASET_NAME": "freshqa", 
    "DATASET_PATH": "Data\\",
    "EVIDENCE_BATCH_SAVE_PATH": "Web_Search_Response\\evidence_results_batch_serp_all_freshqa.json", 
    "QUERY_PROMPT_PATH": "Prompts\\candidate_response.txt", 
    "AUTO_EVALUATION_PROMPT_PATH": "Prompts\\eval_resp_fresh.txt",
    "LLAMA_QUERY_PROMPT_PATH": "Prompts\\candidate_response_meta.txt", 
    "RESULT_SAVE_PATH": "Results\\", 
    "WORKFLOW_RUN_COUNT": 0, 
    "MAX_CANDIDATE_RESPONSES": 3, 
    "MAX_WORKFLOW_RUN_COUNT": 1, 
    "MATCH_CRITERIA": "Half"
}